# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'FragDenStaat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  inherit! :search_paths
  # Pods for FragDenStaat
  pod 'Instabug', '~> 7.0'

  target 'FragDenStaatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

